Repository SOPT-all/35-SOPKATHON-WEB-WEB4, pull requests merged in 2024-11, with the labels that each got.

#1 [setting] theme.ts 세팅
  .github/pull_request_template.md
  src/App.tsx
  src/styles/.gitkeep
  src/styles/theme.ts
  tsconfig.app.json
  vite.config.ts
Labels: enhancement, 화랑 🦁

#2 [setting] GlobalStyle
  src/App.tsx
  src/styles/emotion.d.ts
  src/styles/global.ts
  src/styles/reset.ts
Labels: enhancement, 윤지 🦊

#3 [setting] svgr 설정
  package.json
  src/assets/custom.d.ts
  src/assets/svg/index.ts
  src/vite-env.d.ts
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: enhancement, 영경 🐸

#8 [feat] Modal 컴포넌트 1차 완성
  index.html
  src/components/Modal/Modal.style.ts
  src/components/Modal/Modal.tsx
  src/pages/Posting/Posting.tsx
  src/pages/PostingPage/PostingPage.tsx
  src/pages/PostingPage/components/CompleteModal/CompleteModal.style.ts
  src/pages/PostingPage/components/CompleteModal/CompleteModal.tsx
  src/pages/index.ts
Labels: 민하 🐲

#5 [feat] Header 컴포넌트 1차 완성
  src/components/Header/Header.style.ts
  src/components/Header/Header.tsx
  src/styles/theme.ts
  yarn.lock
Labels: enhancement, 화랑 🦁

#9 [feat] DetailCard 컴포넌트 1차 완성
  src/pages/DetailPage/DetailPage.tsx
  src/pages/DetailPage/components/DetailCard/DetailCard.style.ts
  src/pages/DetailPage/components/DetailCard/DetailCard.tsx
Labels: 민하 🐲

#10 [feat] 랭킹 컴포넌트 구현
  public/svg/ic_failking_1.svg
  public/svg/ic_failking_2.svg
  public/svg/ic_failking_3.svg
  public/svg/ic_failking_4.svg
  public/svg/ic_failking_5.svg
  public/svg/ic_fire.svg
  src/assets/svg/IcFailking1.tsx
  src/assets/svg/IcFailking2.tsx
  src/assets/svg/IcFailking3.tsx
  src/assets/svg/IcFailking4.tsx
  src/assets/svg/IcFailking5.tsx
  src/assets/svg/IcFire.tsx
  src/assets/svg/index.ts
  src/components/RankingCard/Ranking.style.ts
  src/components/RankingCard/RankingCard.tsx
  src/components/RankingSection/RankingSection.style.ts
  src/components/RankingSection/RankingSection.tsx
  src/pages/HomePage/HomePage.tsx
  src/styles/theme.ts
  src/type/rankingCardType.ts
Labels: enhancement, 화랑 🦁

#6 [feat]카드 컴포넌트 1차
  public/svg/img_beer_24.svg
  public/svg/img_good_24.svg
  public/svg/img_pelican_24.svg
  public/svg/img_talented_24.svg
  public/vite.svg
  src/App.tsx
  src/assets/svg/ImgBeer24.tsx
  src/assets/svg/ImgGood24.tsx
  src/assets/svg/ImgPelican24.tsx
  src/assets/svg/ImgTalented24.tsx
  src/assets/svg/index.ts
  src/components/Card/Card.style.ts
  src/components/Card/Card.tsx
  src/components/Emoticon/Emoticon.style.ts
  src/components/Emoticon/Emoticon.tsx
  src/utils/mocks/.gitkeep
Labels: enhancement, 윤지 🦊

#11 [feat] Footer 컴포넌트 2차 완성
  public/svg/ic_addnote_inactive.svg
  public/svg/ic_home_inactive.svg
  public/svg/ic_my_inactive.svg
  src/assets/svg/IcAddnoteInactive.tsx
  src/assets/svg/IcHomeInactive.tsx
  src/assets/svg/IcMyInactive.tsx
  src/assets/svg/index.ts
  src/components/Footer/Footer.style.ts
  src/components/Footer/Footer.tsx
  src/routes/PageRoutes.tsx
Labels: enhancement

#12 [feat] 포스팅페이지 퍼블리싱 완료
  public/svg/ic_arrow_left.svg
  src/assets/svg/IcArrowLeft.tsx
  src/assets/svg/index.ts
  src/components/Footer/Footer.style.ts
  src/components/Header/Header.style.ts
  src/pages/PostingPage/PostingPage.style.ts
  src/pages/PostingPage/PostingPage.tsx
  src/styles/global.ts
  src/styles/theme.ts
Labels: enhancement, 화랑 🦁

#17 [feat] 마이페이지 구성 및 뱃지 부여
  src/pages/MyPage/MyPage.style.ts
  src/pages/MyPage/MyPage.tsx
Labels: enhancement

#20 [feat] 상세페이지 api 연결
  src/components/Card/Card.tsx
  src/pages/DetailPage/DetailPage.tsx
  src/pages/DetailPage/components/DetailCard/DetailCard.style.ts
  src/pages/MyPage/MyPage.tsx
Labels: enhancement
